### PR TITLE
Use capi models v14.2

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Follow-up after having updated frontend.

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
[Update scrooge-core and libthrift](https://trello.com/c/DRpKjlL8/25-update-scrooge-core-and-libthrift)

**Comment by regiskuckaertz** [comment]
Yep, it's all working 🎉

**Comment by philmcmahon** [comment]
Yay! Just for posterity, how come you're able to remove the dependencyOverride stuff and thrift libraries?

**Comment by regiskuckaertz** [comment]
The override was necessary because of a regression in a minor update (`0.9.1` → `0.9.2`), but now that we are using `0.10.0`, this becomes unnecessary. Also I've noticed that if we don't change the model (is why your concierge PR is blocked for now), then it's fine if a producer still encodes using an older version of libthrift 😆

**Comment by philmcmahon** [comment]
oh nice!

**Pull request merged**
