### PR TITLE
Remove unnecessary .json string

### PR DESCRIPTION
**Pull request by frankie297**
## What does this change?
Remove unnecessary .json string, from a copy and paste error from a previous PR. (#15)

### CODE REVIEW

**Review by davidfurey — APPROVED** [review]
LGTM, but it would be reassuring to get @alexduf or @philmcmahon to look at this too.

**Comment by alexduf** [comment]
anyone remembers what value does `event.payloadId` contains?

**Comment by davidfurey** [comment]
`event.payloadId` contains the content id.  See https://github.com/guardian/crier/blob/master/app/com/gu/crier/events/update/ContentUpdateEventHandler.scala#L32

**Review by alexduf — APPROVED** [review]

**Comment by alexduf** [comment]
Thanks! then yes it looks good 👍

**Comment by tonytw1** [comment]
> anyone remembers what value does `event.payloadId` contains?

A CAPI contentId.
ie /travel/2020/blah

**Pull request merged**
