### PR TITLE
Set batch size to 1

### PR DESCRIPTION
**Pull request by tonytw1**
## What does this change?

Change the Lambda consumption batch size to process a single event at once.
Immediately reduces the risk of a single Lambda batch taking too long to process (which jams the entire queue).

Opens the way to sensible dead lettering of single unprocessable events.

This trades some perceived cost and through put considerations for reliability.
This lamda processes ~ 15k events per day and the mean batch size is normally single digits so this is probably ok.

Retire the event deduplication code (which is not applicable on a single event batch).
The deduplication was a tactical workaround to shield downstream consumers (like Facebook) from surges of duplicate content updates.
The upstream root cause of these duplicates has since been addressed so this can be safely removed.

## Have we considered potential risks?

Watch that this doesn't slow through put. The event age metric in cloud watch would be a good indicator of this.

### CODE REVIEW

**Comment by JustinPinner** [comment]
What would the impact of this change be when we do see a larger volume of messages in rapid succession? E.g. in the bulk removal of 200+ content items this morning? Would it mean that regular updates (not part of the bulk operation) just have to wait longer in the queue for their turn at being processed? I guess that's no worse than what happens when an entire batch gets stuck, but are we setting ourselves up to see that more frequently perhaps? The original 100 limit must have had some basis for existing, I just wonder if it was a little too ambitious.

**Comment by tonytw1** [comment]
> What would the impact of this change be when we do see a larger volume of messages in rapid succession? E.g. in the bulk removal of 200+ content items this morning? Would it mean that regular updates (not part of the bulk operation) just have to wait longer in the queue for their turn at being processed? 

Yes; it could potentially display a slightly more sequential behaviour.
Probably not hugely different from the current though; just don't know how .map behaves inside a Lambda.

This is measurable be the max event age metric so we can observe it.
Also separating off the AMP calls into a downstream Lambda would help ensure Fastly decaches remain fast.

**Review by JustinPinner — APPROVED** [review]
Ok, let's see how it goes!

**Comment by AWare** [comment]
I'd like to see a timeout around this as well so the lambda can't time out. We could also set the parallelisation factor a bit higher, which could also stop things getting caught.

**Comment by tonytw1** [comment]
> I'd like to see a timeout around this as well so the lambda can't time out. We could also set the parallelisation factor a bit higher, which could also stop things getting caught.

I've reading Alex's comment as referring to how this Lambda's execution time is unbounded in at least 2 ways:
- The Fastly HTTP calls have no specific timeout set (it's possible that the Lambda execution limit was intended to provide this originally)
- A content item can have any number of aliasPaths

Capping these two variables would help to set a sensible upper bound for execution time.

**Pull request merged**
