### PR TITLE
Replace scalariform with scalafmt

### PR DESCRIPTION
**Pull request by emdash-ie**
## What does this change?

This app currently uses [Scalariform](https://github.com/scala-ide/scalariform) to automatically format the scala code. However, scalariform appears to be unmaintained, and the plugin version we use causes clashes for me locally because it depends on scala-xml v1 while most other things now depend on v2. (I’m not sure why this isn’t broken in CI, actually!)

This PR replaces the uses of scalariform with [scalafmt](https://scalameta.org/scalafmt/), which is currently maintained. It adds a check-formatting step in CI, as well as a scalafmt configuration (currently with nothing specified) and a pre-commit hook to do the formatting.

The pre-commit hook is the same as [the one I added to datawrapper-import](https://github.com/guardian/datawrapper-import/pull/12). It doesn’t use the sbt plugin because of the slow overhead of starting sbt on every commit (in CI using this method avoids needing to install scalafmt, and we’re starting sbt anyway).

There’s also a git-setup script which configures the hooks directory and the git-blame ignore-revs file.

The readme has also been updated to describe the use of scalafmt in the repository.

### Pre-commit hook

- install scalafmt
- run the git config script in ./scripts/git-config.sh
- attempt to commit a change to a scala file that doesn’t obey scalafmt’s formatting (e.g. add some extra spaces in the middle of a line)
- see that the pre-commit hook fails and outputs a helpful message (also formatting the files where possible)

You can test a few other scenarios, e.g. a mixture of scala files and non-scala files, a mixture of staged and unstaged changes, or a scala file that has both staged and unstaged changes (in which case the pre-commit hook won’t clobber the unstaged changes).

### CI

- commit a change that breaks scalafmt (e.g. by not setting up the hook first, or by committing with `--no-verify`
- see that the CI build fails with an explanatory message

### git-blame-ignore-revs file

- (with blame.ignoreRevsFile unset) run git blame on Config.scala, see that at line 15 the commit mentioned is [my formatting commit](https://github.com/guardian/fastly-cache-purger/commit/068dff341387e76412fa2df6d4ae9d0f5b072d34)
- run the git config script (./scripts/git-config.sh)
- rerun the git blame, see that the commit mentioned is now [this commit by Pascal](https://github.com/guardian/fastly-cache-purger/commit/99e306c9327257e01b9975da422e9dd5302926e4)

### CODE REVIEW

**Review by JustinPinner — APPROVED** [review]
Changes look good. I don't like some of the style choices this thing makes, but others are good so 🤷‍♂️ Anyway, as far as this PR goes 👍

**Comment by emdash-ie** [comment]
> Changes look good. I don't like some of the style choices this thing makes, but others are good so 🤷‍♂️ Anyway, as far as this PR goes 👍

Shall we dig into the config options at some point, see if we can arrive at a style you’re happier with? I’m not very attached to particulars of the formatting, I reckon.

**Comment by emdash-ie** [comment]
I’ll deploy this to PROD since the scala files have changed: I don’t expect any change in behaviour, but I think it’s good for PROD to be up to date with main.

**Comment by emdash-ie** [comment]
Deployed to PROD, logs look fine (still purging, no lambda failures).

**Pull request merged**
